#!/usr/bin/php
<?php 
# script based on https://chariosan.com/2019/03/10/php_movie_search_api/

$optind = null;
$options = getopt("aj", array("--all", "--japanese"), $optind);
$title = implode(" ", array_slice($argv, $optind));

# get script path per https://stackoverflow.com/questions/4645082/get-absolute-path-of-initially-run-script
list($scriptPath) = get_included_files();

# read in api key
$apikey_path = dirname($scriptPath)."/.api_key";
if (!file_exists($apikey_path)) {
    echo ".api_key not found\n";
    exit();
}

$apikey = trim(file_get_contents($apikey_path)); //TMDbのAPIキー

# build query
$query = urlencode($title);

$lang = "";
if (isset($options["j"])) {
    $lang = "&language=jp-JA";
}

$url = "https://api.themoviedb.org/3/";
$url .= "search/movie?";
$url .= "api_key=$apikey";
$url .= "&query=$query";
$url .= "&page=1";
$url .= "&include_adult=true";
$url .= $lang;

# get API results
$url_Contents = file_get_contents($url);
$movieArray = json_decode($url_Contents, true);

# check whether we return all results
if (!isset($options["a"])) {
    if (count($movieArray["results"]) > 1) {
        exit();
    }
}

foreach ($movieArray["results"] as $movie) {
    $release_year = substr($movie['release_date'], 0, 4);

    // strip invalid chars per https://stackoverflow.com/questions/2021624/string-sanitizer-for-filename
    $file_name = mb_ereg_replace("([^\w\s\d\-_,;\[\]\(\).])", '', $movie["title"]);
    $file_name = mb_ereg_replace("([\.]{2,})", '', $file_name);

    if (!isset($options["a"])) {
        echo "$file_name ($release_year)\n";
    }
    else {
        echo "$file_name\n";
    }
}

?>
